export interface Product {
  id: string;
  name: string;
  subtitle?: string;
  price: number;
  originalPrice: number;
  category: string;
  rating: number;
  reviews: number;
  discount: number;
  gradientColors: [string, string];
  badge?: string;
  isWishlisted?: boolean;
  description?: string;
  fabric?: string;
  sizes?: string[];
  colors?: string[];
  colorHex?: string[];
  occasion?: string;
  isNew?: boolean;
  isTrending?: boolean;
  isLimitedStock?: boolean;
  isPremium?: boolean;
  deliveryDays?: number;
  pattern?: string;
  material?: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  bgColor: string;
  accentColor: string;
}

export interface Banner {
  id: string;
  title: string;
  subtitle: string;
  cta: string;
  gradientColors: [string, string];
  tag: string;
}

export interface Review {
  id: string;
  name: string;
  rating: number;
  text: string;
  date: string;
  verified: boolean;
}

export interface Order {
  id: string;
  orderId: string;
  date: string;
  status: "Delivered" | "In Transit" | "Processing" | "Cancelled";
  items: { name: string; qty: number; price: number }[];
  total: number;
  tracking: string | null;
}

export const BANNERS: Banner[] = [
  {
    id: "1",
    title: "Festival Season",
    subtitle: "Premium silk sarees up to 60% off",
    cta: "Shop Now",
    gradientColors: ["#6B1A1A", "#2C1206"],
    tag: "Limited Time",
  },
  {
    id: "2",
    title: "New Arrivals",
    subtitle: "Bridal lehenga collection 2025",
    cta: "Explore",
    gradientColors: ["#8B6914", "#C9A84C"],
    tag: "Just In",
  },
  {
    id: "3",
    title: "Silver Jewels",
    subtitle: "Handcrafted 925 silver jewellery",
    cta: "View All",
    gradientColors: ["#3A3A4A", "#5A5A6A"],
    tag: "Exclusive",
  },
];

export const CATEGORIES: Category[] = [
  { id: "1", name: "Women", icon: "woman", bgColor: "#FDEEE8", accentColor: "#6B1A1A" },
  { id: "2", name: "Men", icon: "man", bgColor: "#E8EDF5", accentColor: "#1A2C6B" },
  { id: "3", name: "Kids", icon: "happy", bgColor: "#E8F5E8", accentColor: "#1A6B1A" },
  { id: "4", name: "Silver", icon: "diamond", bgColor: "#EBEBEB", accentColor: "#505060" },
  { id: "5", name: "Festival", icon: "star", bgColor: "#FDF5E0", accentColor: "#C9A84C" },
  { id: "6", name: "Bridal", icon: "heart", bgColor: "#FDEBEB", accentColor: "#8B0000" },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Kanjivaram Silk Saree",
    subtitle: "Pure silk with zari border",
    price: 4299,
    originalPrice: 5999,
    category: "Women",
    rating: 4.8,
    reviews: 234,
    discount: 28,
    gradientColors: ["#6B1A1A", "#2C1206"],
    badge: "Bestseller",
    description: "Pure Kanjivaram silk with traditional zari work. A timeless piece for every special occasion.",
    fabric: "100% Pure Silk",
    material: "Silk",
    sizes: ["Free Size"],
    colors: ["Maroon", "Navy", "Green"],
    colorHex: ["#6B1A1A", "#1A2C6B", "#1A6B1A"],
    occasion: "Wedding",
    isPremium: true,
    deliveryDays: 3,
    pattern: "Zari",
  },
  {
    id: "2",
    name: "Banarasi Handloom",
    subtitle: "Gold thread weaved heritage",
    price: 3599,
    originalPrice: 4800,
    category: "Women",
    rating: 4.6,
    reviews: 187,
    discount: 25,
    gradientColors: ["#C9A84C", "#8B6914"],
    badge: "New",
    isNew: true,
    description: "Authentic Banarasi handloom with intricate gold thread weaving.",
    fabric: "Silk Cotton Blend",
    material: "Silk Cotton",
    sizes: ["Free Size"],
    colors: ["Gold", "Red", "Blue"],
    colorHex: ["#C9A84C", "#8B0000", "#1A2C6B"],
    occasion: "Festival",
    deliveryDays: 2,
    pattern: "Brocade",
  },
  {
    id: "3",
    name: "Bridal Lehenga Set",
    subtitle: "Heavy embroidery couture",
    price: 12999,
    originalPrice: 18000,
    category: "Women",
    rating: 4.9,
    reviews: 89,
    discount: 28,
    gradientColors: ["#8B0000", "#3D0000"],
    badge: "Premium",
    isPremium: true,
    isLimitedStock: true,
    description: "Exquisite bridal lehenga with heavy embroidery and premium fabric.",
    fabric: "Georgette with Silk Lining",
    material: "Georgette",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Red", "Pink", "Maroon"],
    colorHex: ["#8B0000", "#C8536B", "#6B1A1A"],
    occasion: "Bridal",
    deliveryDays: 5,
    pattern: "Embroidery",
  },
  {
    id: "4",
    name: "Men's Sherwani",
    subtitle: "Regal ceremonial attire",
    price: 6599,
    originalPrice: 8500,
    category: "Men",
    rating: 4.7,
    reviews: 156,
    discount: 22,
    gradientColors: ["#2C1206", "#1A0800"],
    badge: "Top Pick",
    isTrending: true,
    description: "Regal sherwani with traditional embroidery. Perfect for weddings and celebrations.",
    fabric: "Raw Silk",
    material: "Silk",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Ivory", "Maroon"],
    colorHex: ["#1A1A1A", "#FFFFF0", "#6B1A1A"],
    occasion: "Wedding",
    isPremium: true,
    deliveryDays: 4,
    pattern: "Plain",
  },
  {
    id: "5",
    name: "Pattu Pavadai",
    subtitle: "Festive silk for little ones",
    price: 1899,
    originalPrice: 2500,
    category: "Kids",
    rating: 4.5,
    reviews: 203,
    discount: 24,
    gradientColors: ["#D4826A", "#9C4B35"],
    description: "Beautiful silk pavadai for little ones. Perfect for festivals and functions.",
    fabric: "Silk",
    material: "Silk",
    sizes: ["2Y", "4Y", "6Y", "8Y", "10Y"],
    colors: ["Red", "Green", "Pink"],
    colorHex: ["#8B0000", "#1A6B1A", "#C8536B"],
    occasion: "Festival",
    deliveryDays: 3,
    pattern: "Temple",
  },
  {
    id: "6",
    name: "Silver Chain Necklace",
    subtitle: "925 sterling artisan craft",
    price: 899,
    originalPrice: 1200,
    category: "Silver",
    rating: 4.6,
    reviews: 312,
    discount: 25,
    gradientColors: ["#808090", "#505060"],
    badge: "Trending",
    isTrending: true,
    description: "925 sterling silver chain with delicate pendant. Handcrafted by artisans.",
    fabric: "925 Sterling Silver",
    material: "Silver",
    sizes: ["16 inch", "18 inch", "20 inch"],
    colors: ["Silver"],
    colorHex: ["#C0C0C0"],
    occasion: "Daily Wear",
    deliveryDays: 2,
    pattern: "Chain",
  },
  {
    id: "7",
    name: "Chudidar Suit Set",
    subtitle: "Elegant ethnic ensemble",
    price: 2299,
    originalPrice: 3200,
    category: "Women",
    rating: 4.4,
    reviews: 178,
    discount: 28,
    gradientColors: ["#1A5C6B", "#0D3B45"],
    description: "Elegant chudidar set with matching dupatta and churidar.",
    fabric: "Cotton Silk",
    material: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Teal", "Blue", "Purple"],
    colorHex: ["#1A5C6B", "#1A2C6B", "#5C1A6B"],
    occasion: "Office Wear",
    deliveryDays: 2,
    pattern: "Printed",
  },
  {
    id: "8",
    name: "Pure Cotton Saree",
    subtitle: "Breathable everyday elegance",
    price: 1499,
    originalPrice: 2000,
    category: "Women",
    rating: 4.3,
    reviews: 145,
    discount: 25,
    gradientColors: ["#4A7C59", "#2C5C3A"],
    badge: "Eco",
    description: "Soft pure cotton saree, ideal for everyday wear.",
    fabric: "100% Pure Cotton",
    material: "Cotton",
    sizes: ["Free Size"],
    colors: ["Green", "White", "Orange"],
    colorHex: ["#4A7C59", "#F5F5F5", "#D4826A"],
    occasion: "Casual",
    deliveryDays: 2,
    pattern: "Checks",
  },
  {
    id: "9",
    name: "Mysore Silk Saree",
    subtitle: "Royal Karnataka heritage",
    price: 5499,
    originalPrice: 7200,
    category: "Women",
    rating: 4.7,
    reviews: 98,
    discount: 24,
    gradientColors: ["#5C1A6B", "#3A0D45"],
    badge: "New",
    isNew: true,
    description: "Soft, lustrous Mysore silk with elegant zari border. A classic collectible.",
    fabric: "Pure Mysore Silk",
    material: "Silk",
    sizes: ["Free Size"],
    colors: ["Purple", "Maroon", "Blue"],
    colorHex: ["#5C1A6B", "#6B1A1A", "#1A2C6B"],
    occasion: "Wedding",
    isPremium: true,
    deliveryDays: 3,
    pattern: "Zari",
  },
  {
    id: "10",
    name: "Anarkali Suit",
    subtitle: "Mughal-inspired floor-length",
    price: 3199,
    originalPrice: 4500,
    category: "Women",
    rating: 4.5,
    reviews: 212,
    discount: 29,
    gradientColors: ["#C8536B", "#8B1A35"],
    isTrending: true,
    description: "Flowing Anarkali suit with intricate embroidery and flared silhouette.",
    fabric: "Georgette",
    material: "Georgette",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Rose", "Mint", "Peach"],
    colorHex: ["#C8536B", "#1A6B4A", "#D4826A"],
    occasion: "Party Wear",
    deliveryDays: 3,
    pattern: "Embroidery",
  },
  {
    id: "11",
    name: "Kids Lehenga Choli",
    subtitle: "Festival princess look",
    price: 1299,
    originalPrice: 1800,
    category: "Kids",
    rating: 4.6,
    reviews: 167,
    discount: 28,
    gradientColors: ["#C9A84C", "#8B6914"],
    badge: "Trending",
    isTrending: true,
    description: "Adorable lehenga choli for little girls with mirror work and lace detailing.",
    fabric: "Net over Satin",
    material: "Satin",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
    colors: ["Gold", "Pink", "Green"],
    colorHex: ["#C9A84C", "#C8536B", "#1A6B1A"],
    occasion: "Festival",
    deliveryDays: 2,
    pattern: "Mirror Work",
  },
  {
    id: "12",
    name: "Silver Bangles Set",
    subtitle: "Handcrafted traditional design",
    price: 1599,
    originalPrice: 2200,
    category: "Silver",
    rating: 4.8,
    reviews: 289,
    discount: 27,
    gradientColors: ["#A0A0B0", "#606070"],
    badge: "Bestseller",
    isLimitedStock: true,
    description: "Set of 6 pure silver bangles with traditional embossed patterns.",
    fabric: "Pure Silver",
    material: "Silver",
    sizes: ["2.4", "2.6", "2.8"],
    colors: ["Silver", "Antique"],
    colorHex: ["#C0C0C0", "#8B7355"],
    occasion: "Wedding",
    deliveryDays: 3,
    pattern: "Traditional",
  },
  {
    id: "13",
    name: "Men's Kurta Pyjama",
    subtitle: "Classic celebration set",
    price: 1899,
    originalPrice: 2600,
    category: "Men",
    rating: 4.4,
    reviews: 321,
    discount: 27,
    gradientColors: ["#1A2C6B", "#0D1A45"],
    description: "Premium cotton kurta with matching pyjama set. Perfect for casual celebrations.",
    fabric: "Pure Cotton",
    material: "Cotton",
    sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
    colors: ["White", "Blue", "Cream"],
    colorHex: ["#F5F5F5", "#1A2C6B", "#F5EDD6"],
    occasion: "Casual",
    deliveryDays: 2,
    pattern: "Printed",
  },
  {
    id: "14",
    name: "Navratri Chaniya Choli",
    subtitle: "Garba night special edition",
    price: 2799,
    originalPrice: 4000,
    category: "Festival",
    rating: 4.7,
    reviews: 143,
    discount: 30,
    gradientColors: ["#D4826A", "#8B3A1A"],
    badge: "Festival",
    isNew: true,
    description: "Vibrant chaniya choli with mirror work and colorful embroidery for garba nights.",
    fabric: "Cotton Blend",
    material: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Orange", "Red", "Green"],
    colorHex: ["#D4826A", "#8B0000", "#1A6B1A"],
    occasion: "Festival",
    deliveryDays: 2,
    pattern: "Mirror Work",
  },
  {
    id: "15",
    name: "Patola Silk Dupatta",
    subtitle: "Double ikat weave luxury",
    price: 2499,
    originalPrice: 3500,
    category: "Women",
    rating: 4.5,
    reviews: 76,
    discount: 29,
    gradientColors: ["#1A6B4A", "#0D4530"],
    badge: "Exclusive",
    isPremium: true,
    isLimitedStock: true,
    description: "Handwoven Patola dupatta with traditional double ikat technique. Each piece is unique.",
    fabric: "Pure Silk",
    material: "Silk",
    sizes: ["Free Size"],
    colors: ["Emerald", "Burgundy", "Saffron"],
    colorHex: ["#1A6B4A", "#6B1A1A", "#D4826A"],
    occasion: "Wedding",
    deliveryDays: 5,
    pattern: "Ikat",
  },
  {
    id: "16",
    name: "Silver Earrings Set",
    subtitle: "Jhumka collection 2025",
    price: 699,
    originalPrice: 999,
    category: "Silver",
    rating: 4.6,
    reviews: 445,
    discount: 30,
    gradientColors: ["#6B6B7B", "#404050"],
    isTrending: true,
    description: "Elegant silver jhumka earrings with stone inlay. Lightweight and perfect for daily wear.",
    fabric: "Silver + Stones",
    material: "Silver",
    sizes: ["One Size"],
    colors: ["Silver", "Gold", "Rose Gold"],
    colorHex: ["#C0C0C0", "#C9A84C", "#B76E79"],
    occasion: "Daily Wear",
    deliveryDays: 2,
    pattern: "Jhumka",
  },
  {
    id: "17",
    name: "Boys Dhoti Kurta",
    subtitle: "Traditional ceremony wear",
    price: 999,
    originalPrice: 1400,
    category: "Kids",
    rating: 4.4,
    reviews: 134,
    discount: 29,
    gradientColors: ["#C9A84C", "#6B5520"],
    description: "Classic dhoti-kurta set for young boys. Perfect for weddings and religious ceremonies.",
    fabric: "Cotton Blend",
    material: "Cotton",
    sizes: ["2Y", "4Y", "6Y", "8Y", "10Y", "12Y"],
    colors: ["Cream", "White", "Gold"],
    colorHex: ["#F5EDD6", "#F5F5F5", "#C9A84C"],
    occasion: "Wedding",
    deliveryDays: 3,
    pattern: "Plain",
  },
  {
    id: "18",
    name: "Chikankari Kurti",
    subtitle: "Lucknow's finest hand work",
    price: 1799,
    originalPrice: 2400,
    category: "Women",
    rating: 4.6,
    reviews: 267,
    discount: 25,
    gradientColors: ["#5C8B7A", "#2C5C4A"],
    badge: "Trending",
    isTrending: true,
    description: "Hand embroidered chikankari kurti from Lucknow artisans. Breathable and elegant.",
    fabric: "Muslin Cotton",
    material: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Pastel Pink", "Sky Blue"],
    colorHex: ["#F5F5F5", "#F5B8C0", "#87CEEB"],
    occasion: "Casual",
    deliveryDays: 2,
    pattern: "Chikankari",
  },
  {
    id: "19",
    name: "Wedding Shawl",
    subtitle: "Kashmiri pashmina luxury",
    price: 3999,
    originalPrice: 5500,
    category: "Women",
    rating: 4.8,
    reviews: 56,
    discount: 27,
    gradientColors: ["#8B3A6B", "#5C1A45"],
    badge: "Premium",
    isPremium: true,
    isLimitedStock: true,
    description: "Authentic Kashmiri pashmina shawl with traditional paisley embroidery.",
    fabric: "Pure Pashmina",
    material: "Pashmina",
    sizes: ["Free Size"],
    colors: ["Ivory", "Maroon", "Teal"],
    colorHex: ["#FFFFF0", "#6B1A1A", "#1A5C6B"],
    occasion: "Bridal",
    isPremium: true,
    deliveryDays: 4,
    pattern: "Paisley",
  },
  {
    id: "20",
    name: "Men's Nehru Jacket",
    subtitle: "Modern Indian fusion",
    price: 2499,
    originalPrice: 3400,
    category: "Men",
    rating: 4.5,
    reviews: 189,
    discount: 26,
    gradientColors: ["#3A5C2C", "#1A3A0D"],
    isNew: true,
    description: "Elegant Nehru jacket in premium fabric. Perfect for festive gatherings.",
    fabric: "Brocade",
    material: "Brocade",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Bottle Green", "Navy", "Maroon"],
    colorHex: ["#3A5C2C", "#1A2C6B", "#6B1A1A"],
    occasion: "Festival",
    deliveryDays: 3,
    pattern: "Woven",
  },
  {
    id: "21",
    name: "Kalamkari Saree",
    subtitle: "Folk art on silk canvas",
    price: 2899,
    originalPrice: 3800,
    category: "Women",
    rating: 4.4,
    reviews: 112,
    discount: 24,
    gradientColors: ["#8B6B2C", "#5C4A1A"],
    badge: "Artisan",
    description: "Hand painted Kalamkari saree with mythological motifs by Andhra artisans.",
    fabric: "Natural Dyed Silk",
    material: "Silk",
    sizes: ["Free Size"],
    colors: ["Ochre", "Indigo", "Natural"],
    colorHex: ["#C9A84C", "#1A2C6B", "#D4C5A9"],
    occasion: "Casual",
    deliveryDays: 3,
    pattern: "Kalamkari",
  },
  {
    id: "22",
    name: "Silver Anklets",
    subtitle: "Ghungroo charm collection",
    price: 549,
    originalPrice: 799,
    category: "Silver",
    rating: 4.5,
    reviews: 378,
    discount: 31,
    gradientColors: ["#909090", "#606060"],
    isTrending: true,
    description: "Pair of pure silver anklets with traditional ghungroo bells. Handmade.",
    fabric: "Pure Silver",
    material: "Silver",
    sizes: ["Small", "Medium", "Large"],
    colors: ["Silver"],
    colorHex: ["#C0C0C0"],
    occasion: "Daily Wear",
    deliveryDays: 2,
    pattern: "Traditional",
  },
  {
    id: "23",
    name: "Diwali Kurta Set",
    subtitle: "Festive glow collection",
    price: 2199,
    originalPrice: 3000,
    category: "Festival",
    rating: 4.6,
    reviews: 234,
    discount: 27,
    gradientColors: ["#C9A84C", "#8B6B14"],
    badge: "Festival",
    isNew: true,
    description: "Vibrant kurta set specially curated for Diwali celebrations. Comes with matching accessories.",
    fabric: "Rayon Blend",
    material: "Rayon",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Yellow", "Orange", "Gold"],
    colorHex: ["#F5D020", "#D4826A", "#C9A84C"],
    occasion: "Festival",
    deliveryDays: 2,
    pattern: "Printed",
  },
  {
    id: "24",
    name: "Embroidered Blouse",
    subtitle: "Heirloom quality craftsmanship",
    price: 1299,
    originalPrice: 1800,
    category: "Women",
    rating: 4.7,
    reviews: 156,
    discount: 28,
    gradientColors: ["#6B1A4A", "#3D0D2C"],
    badge: "New",
    isNew: true,
    description: "Hand-embroidered silk blouse with mirror work and stone detailing. Pairs with any saree.",
    fabric: "Raw Silk",
    material: "Silk",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Magenta", "Teal", "Navy"],
    colorHex: ["#C8536B", "#1A5C6B", "#1A2C6B"],
    occasion: "Party Wear",
    deliveryDays: 3,
    pattern: "Mirror Work",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "1",
    name: "Priya Sharma",
    rating: 5,
    text: "Absolutely stunning quality! The Kanjivaram saree I ordered was exactly as shown. Fast delivery and beautiful packaging. Will definitely order again!",
    date: "2 days ago",
    verified: true,
  },
  {
    id: "2",
    name: "Meena Krishnan",
    rating: 5,
    text: "Best saree shop! The fabric quality is exceptional and the designs are timeless. The team was very helpful with sizing.",
    date: "1 week ago",
    verified: true,
  },
  {
    id: "3",
    name: "Anjali Nair",
    rating: 4,
    text: "Lovely collection of festival wear. Got a beautiful lehenga for my daughter's function. Very happy with the purchase!",
    date: "2 weeks ago",
    verified: true,
  },
];

export const ORDERS: Order[] = [
  {
    id: "1",
    orderId: "KRM2024001",
    date: "Dec 15, 2024",
    status: "Delivered",
    items: [{ name: "Kanjivaram Silk Saree", qty: 1, price: 4299 }],
    total: 4299,
    tracking: "TN123456789IN",
  },
  {
    id: "2",
    orderId: "KRM2024002",
    date: "Dec 20, 2024",
    status: "In Transit",
    items: [
      { name: "Bridal Lehenga Set", qty: 1, price: 12999 },
      { name: "Silver Chain Necklace", qty: 1, price: 899 },
    ],
    total: 13898,
    tracking: "TN987654321IN",
  },
  {
    id: "3",
    orderId: "KRM2024003",
    date: "Dec 22, 2024",
    status: "Processing",
    items: [{ name: "Men's Sherwani", qty: 1, price: 6599 }],
    total: 6599,
    tracking: null,
  },
];

export const TRENDING_SEARCHES = [
  "Silk Sarees",
  "Bridal Lehenga",
  "Silver Jewellery",
  "Festival Wear",
  "Kanjivaram",
  "Pattu Sarees",
  "Sherwani",
  "Chudidar",
];

export const RECENT_SEARCHES = ["Kanjivaram", "Gold jewellery", "Kids pattu"];
